package eu.enact.greencharge;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.Map;

/**
 * Liveness/readiness endpoint on the application port.
 *
 * <p>Charts generated by the ENACT SDK's Application Packaging always probe
 * {@code /health} on the container port; without this endpoint the generated
 * chart's probes fail and the pod restarts in a loop.
 */
@RestController
public class HealthController {

    @GetMapping("/health")
    public Map<String, String> health() {
        return Map.of("status", "UP");
    }
}
